local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Pop It Script v2.2", "Ocean")

local Tab = Window:NewTab("main")
local Section = Tab:NewSection("main")
Section:NewTextBox("Buy Any Item", "Type in the box what you want then hit enter", function(txt)
    print(txt)
    local args = {
        [1] = (txt)
    }
    
    game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
end)
Section:NewToggle("Auto Water Melon", "auto equip water melon loop", function(state)
    if state then
        print("Toggle On")
        getgenv().farmer = true;

while wait(1) do
    if getgenv().farmer == true then
      -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Watermelon"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

   end
end
    else
        print("Toggle Off")
        getgenv().farmer = false;

while wait(1) do
    if getgenv().farmer == true then
      -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Watermelon"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

   end
end
    end
end)
Section:NewToggle("Crasher", "wait 30 to 40 seconds while this is active", function(state)
    if state then
        print("Toggle On")
        getgenv().farmers = true;

while wait(0) do
    if getgenv().farmers == true then
        
local args = {
    [1] = "Jet"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().farmers = false;

while wait(0) do
    if getgenv().farmers == true then
        
local args = {
    [1] = "Jet"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    end
end)
local Section = Tab:NewSection("Auto Dropper")
Section:NewToggle("Auto Drop The Banana", "auto drops the banana", function(state)
    if state then
        print("Toggle On")
        getgenv().farme = true;

while wait(1) do
    if getgenv().farme == true then
        local args = {
            [1] = "The banana"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
        wait(1)
         local args = {
            [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().farme = false;

while wait(1) do
    if getgenv().farme == true then
        local args = {
            [1] = "The banana"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
        wait(1)
         local args = {
            [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    end
end)
Section:NewToggle("Auto Drop Trading Ben", "auto drops trading ben", function(state)
    if state then
        print("Toggle On")
        getgenv().farmerr = true;

while wait(1) do
    if getgenv().farmerr == true then
        local args = {
    [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
wait(1)
local args = {
    [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().farmerr = false;

while wait(1) do
    if getgenv().farmerr == true then
        local args = {
    [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
local args = {
    [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    end
end)
Section:NewToggle("Auto Drop Mommeh Long Legs", "ToggleInfo", function(state)
    if state then
        print("Toggle On")
        getgenv().farmerdd = true;

        while wait(1) do
            if getgenv().farmerdd == true then
                
        local args = {
            [1] = "Mommeh Long Legs"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
        wait(1)
        
        local args = {
            [1] = "Mommeh Long Legs"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))
        
            end
        end
    else
        print("Toggle Off")
        getgenv().farmerdd = false;

while wait(1) do
    if getgenv().farmerdd == true then
        
local args = {
    [1] = "Mommeh Long Legs"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
wait(1)

local args = {
    [1] = "Mommeh Long Legs"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    end
end)
Section:NewToggle("Auto Drop Munneh", "auto drops munneh", function(state)
    if state then
        print("Toggle On")
        getgenv().fa = true;

while wait(1) do
    if getgenv().fa == true then
        
local args = {
    [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
wait(1)

local args = {
    [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().fa = false;

while wait(1) do
    if getgenv().fa == true then
        
local args = {
    [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))
wait(1)

local args = {
    [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.Drop:FireServer(unpack(args))

    end
end
    end
end)
local Section = Tab:NewSection("Buy NFTS")
Section:NewToggle("Buy The Banana Multiple", "buys trading bananas very fast", function(state)
    if state then
        print("Toggle On")
        getgenv().fas = true;

        while wait(0) do
            if getgenv().fas == true then
                local args = {
                [1] = "The banana"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
        
            end
        end
    else
        print("Toggle Off")
        getgenv().fas = false;

while wait(0) do
    if getgenv().fas == true then
        local args = {
        [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    end
end)
Section:NewButton("Buy The banana Single", "buy the banana one at a time", function()
    print("Clicked")
    local args = {
        [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
end)
Section:NewToggle("Buy Trading Ben Multiple", "buys trading Ben very fast", function(state)
    if state then
        print("Toggle On")
        getgenv().f = true;

        while wait(0) do
            if getgenv().f == true then
                local args = {
                [1] = "Trading Ben"
        }
        
        game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
        
            end
        end
    else
        print("Toggle Off")
        getgenv().f = false;

while wait(0) do
    if getgenv().f == true then
        local args = {
        [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    end
end)
Section:NewButton("Buy Trading Ben Single", "buy trading bens one at a time", function()
    print("Clicked")
    local args = {
        [1] = "Trading Ben"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
end)

Section:NewToggle("Buy Mommeh Long Legs Multiple", "buys mummeh long leg very fast", function(state)
    if state then
        print("Toggle On")
        getgenv().a = true;

while wait(0) do
    if getgenv().a == true then
        local args = {
        [1] = "Mommeh Long Legs"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().a = false;

while wait(0) do
    if getgenv().a == true then
        local args = {
        [1] = "Mommeh Long Legs"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

    end
end
    end
end)
Section:NewButton("Buy Mommeh Long Legs Single", "buys mummeh long legs one at a time", function()
    print("Clicked")
    local args = {
        [1] = "Mommeh Long Legs"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
end)
Section:NewToggle("Buy Munneh Multiple", "buys munneh rlly fast", function(state)
    if state then
        print("Toggle On")
        getgenv().farmer = true;

while wait(0) do
    if getgenv().farmer == true then
        local args = {
        [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
    end
end
    else
        print("Toggle Off")
        getgenv().farmer = false;

while wait(0) do
    if getgenv().farmer == true then
        local args = {
        [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
    end
end
    end
end)
Section:NewButton("Buy Munneh Single", "buys muneneh one at a time", function()
    print("Clicked")
    local args = {
        [1] = "Munneh"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))
end)
local Section = Tab:NewSection("Money Dupe")
Section:NewToggle("Use The Bananas ", "uses the banana for the dupe", function(state)
    if state then
        print("Toggle On")
        getgenv().farmest = true;

while wait(1) do
    if getgenv().farmest == true then
        
local args = {
    [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

    end
end

    else
        print("Toggle Off")
        getgenv().farmest = false;

while wait(1) do
    if getgenv().farmest == true then
        
local args = {
    [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "The banana"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "The banana"
}
    end
end
    end
end)
Section:NewToggle("Use Pop It Rainbow!", "uses pop it for the money", function(state)
    if state then
        print("Toggle On")
        getgenv().z = true;

while wait(1) do
    if getgenv().z == true then
        
local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().z = false;

while wait(1) do
    if getgenv().z == true then
        
local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "Pop It Rainbow!"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

    end
end
    end
end)
Section:NewToggle("Use Amongus Rainbow", "uses rainbow amongus for money exploit", function(state)
    if state then
        print("Toggle On")
        getgenv().n = true;

while wait(1) do
    if getgenv().n == true then
        
local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

    end
end
    else
        print("Toggle Off")
        getgenv().n = false;

while wait(1) do
    if getgenv().n == true then
        
local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.Sell:FireServer(unpack(args))

local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.BuyItemCash:FireServer(unpack(args))

local args = {
    [1] = "Amogus Rainbow"
}

game:GetService("ReplicatedStorage").RemoteEvents.Equip:FireServer(unpack(args))

    end
end
    end
end)
local Tab = Window:NewTab("Misc")
local Misc = Tab:NewSection("Misc")
Misc:NewButton("E to fly script", "Makes you fly", function()
        loadstring(game:HttpGet(('https://pastebin.com/raw/KtLKcbxr'),true))()
    print("Clicked")
end)
Misc:NewSlider("WalkSpeed", "makes speed faster monke", 500, 0, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = s
end)
Misc:NewSlider("JumpPower", "your dumb", 500, 0, function(s) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = s
end)
Misc:NewKeybind("Make a bind to open and close GUI", "open n close ui", Enum.KeyCode.F, function()
    Library:ToggleUI()
end)
local Tab = Window:NewTab("Info")
local Info = Tab:NewSection("Info")
Info:NewTextBox("Made by 16#0001", "TextboxInfo", function(txt)
    print(txt)
end)
